### ISSUE TITLE
nanpy and Python 3.4.2 (rPi)

### ISSUE THREAD

**Issue by ash73** [nanpy/nanpy#85]
Hi, I've installed nanpy on a rPi2/Arduino Uno and it works ok in Python 2.7.9, but when I try to use it in Python 3.4.2 I get an error message:

from nanpy import ArduinoApi
Traceback (most recent call last):
  File "<pyshell#0>", line 1, in <module>
    from nanpy import ArduinoApi
ImportError: cannot import name 'ArduinoApi'

Any suggestions?

**Comment by ash73** [comment]
Nevermind, got it working :)
