### ISSUE TITLE
Compilation error in Arduino 1.8.3

### ISSUE THREAD

**Issue by tanvirs27** [nanpy/nanpy#98]
This library works fine in Arduino 1.0.5, but now it shows these errors when I try to build it (using verify) in Arduino 1.8.3  

```
In file included from sketch/cfg_all.h:5:0,
                 from sketch/BaseClass.h:4,
                 from sketch/ArduinoClass.h:4,
                 from sketch/ArduinoClass.cpp:2:
sketch/cfg_check.h:7:0: warning: "USE_ArduinoCore" redefined [enabled by default]
 #define USE_ArduinoCore                             0
 ^
In file included from sketch/cfg_all.h:3:0,
                 from sketch/BaseClass.h:4,
                 from sketch/ArduinoClass.h:4,
                 from sketch/ArduinoClass.cpp:2:
sketch/cfg.h:24:0: note: this is the location of the previous definition
 #define USE_ArduinoCore                             1
 ^
In file included from sketch/cfg_all.h:5:0,
                 from sketch/BaseClass.h:4,
                 from sketch/ArduinoClass.h:4,
                 from sketch/ArduinoClass.cpp:2:
sketch/cfg_check.h:9:0: warning: "USE_EEPROM" redefined [enabled by default]
 #define USE_EEPROM                                  0
 ^
In file included from sketch/cfg_all.h:3:0,
                 from sketch/BaseClass.h:4,
                 from sketch/ArduinoClass.h:4,
                 from sketch/ArduinoClass.cpp:2:
sketch/cfg.h:30:0: note: this is the location of the previous definition
 #define USE_EEPROM                                  1
 ^
sketch/ArduinoClass.cpp: In member function ‘virtual void nanpy::ArduinoClass::elaborate(nanpy::MethodDescriptor*)’:
ArduinoClass.cpp:40: error: call of overloaded ‘returns(uint64_t)’ is ambiguous
             m->returns(millis());
                                ^
sketch/ArduinoClass.cpp:40:32: note: candidates are:
In file included from sketch/BaseClass.h:6:0,
                 from sketch/ArduinoClass.h:4,
                 from sketch/ArduinoClass.cpp:2:
sketch/MethodDescriptor.h:32:18: note: void nanpy::MethodDescriptor::returns(const char*) <near match>
             void returns(const char* val);
                  ^
sketch/MethodDescriptor.h:32:18: note:   no known conversion for argument 1 from ‘uint64_t {aka long long unsigned int}’ to ‘const char*’
sketch/MethodDescriptor.h:33:18: note: void nanpy::MethodDescriptor::returns(char)
             void returns(char val);
                  ^
sketch/MethodDescriptor.h:34:18: note: void nanpy::MethodDescriptor::returns(unsigned char)
             void returns(unsigned char val);
                  ^
sketch/MethodDescriptor.h:35:18: note: void nanpy::MethodDescriptor::returns(int)
             void returns(int val);
                  ^
sketch/MethodDescriptor.h:36:18: note: void nanpy::MethodDescriptor::returns(unsigned int)
             void returns(unsigned int val);
                  ^
sketch/MethodDescriptor.h:37:18: note: void nanpy::MethodDescriptor::returns(float)
             void returns(float val);
                  ^
sketch/MethodDescriptor.h:38:18: note: void nanpy::MethodDescriptor::returns(double)
             void returns(double val);
                  ^
sketch/MethodDescriptor.h:39:18: note: void nanpy::MethodDescriptor::returns(long int)
             void returns(long val);
                  ^
sketch/MethodDescriptor.h:40:18: note: void nanpy::MethodDescriptor::returns(long unsigned int)
             void returns(unsigned long val);
                  ^
exit status 1
call of overloaded ‘returns(uint64_t)’ is ambiguous

```
